doctrine:
    orm:
        mappings:
            WebeakMailBundle:
                type: annotation
                dir: "Bridge/Doctrine/Orm/Entity"
                alias: MailBundle
                prefix: "Webeak\\Bundle\\MailBundle\\Bridge\\Doctrine\\Orm\\Entity"
                is_bundle: true
