services:
    _defaults:
        autowire: true
        autoconfigure: true

    #
    # Transports
    #
    Webeak\Bundle\MailBundle\Transport\TipimailTransportFactory:
        tags: ['mailer.transport_factory']

    #
    # Decorators
    #
    Webeak\Bundle\MailBundle\Transport\TrackedTransportFactoryDecorator.base:
        class: Webeak\Bundle\MailBundle\Transport\TrackedTransportFactoryDecorator
        autoconfigure: false
        arguments:
            - '@logger'
            - '@doctrine'

    # Decorator for Tipimail
    Webeak\Bundle\MailBundle\Transport\TrackedTransportFactoryDecorator.tipimail:
        parent: Webeak\Bundle\MailBundle\Transport\TrackedTransportFactoryDecorator.base
        decorates: 'Webeak\Bundle\MailBundle\Transport\TipimailTransportFactory'
        arguments:
            - '@.inner'

    # Decorator for the default SMTP transport
    Webeak\Bundle\MailBundle\Transport\TrackedTransportFactoryDecorator.smtp:
        parent: Webeak\Bundle\MailBundle\Transport\TrackedTransportFactoryDecorator.base
        decorates: 'mailer.transport_factory.smtp'
        arguments:
            - '@.inner'
        tags: ['mailer.transport_factory']

    #
    # Event subscribers
    #
    Webeak\Bundle\MailBundle\EventSubscriber\:
        resource: '../../EventSubscriber'
        tags: [ { name: kernel.event_subscriber } ]
